#version 450

struct VertexIn {
    vec3 position;
    vec3 color; 
    vec3 normal;
};

layout(std430, binding = 0) readonly buffer InBuffer {
    VertexIn inVertices[];
};

layout(std430, binding = 1) buffer OutBuffer {
    float brightness[];
};

layout (binding = 2) uniform UniformBufferObject {
    mat4 model;
    mat4 view;
    mat4 proj;
} ubo;

layout (local_size_x = 256) in;

void main() {
    uint idx = gl_GlobalInvocationID.x;

    vec3 normal = normalize(inVertices[idx].normal);
    vec3 lightDir = normalize(vec3(0.4, 0.8, 0.6));
    brightness[idx] = max(dot(normal, lightDir), 0.0);
}